name: update-gh-activity

on:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: squishykins/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}